version: '3.7'
services:
  frontend:
    image: nginx:latest
    container_name: frontend
    volumes:
      - ./dist/cinema-frontend:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf.d/web.conf:/etc/nginx/conf.d/web.conf
      - ./config/nginx/cert:/etc/ssl
    ports:
      - 8080:80
      - 4443:443
    restart: always
    links:
      - php
